---
- hosts: localhost
  tasks:
  - name: Sincronizar archivos
    become: true
    ansible.builtin.synchronize:
      src: /home/pi/.ansible/pull/pi/
      dest: /var/www/html/
      links: yes
  - name: Recargar nginx
    become: true
    ansible.builtin.service:
      name: nginx
      state: reloaded
      enabled: true