---
- hosts: localhost
  tasks:
  - name: Sincronizar archivos
    become: true
    ansible.builtin.synchronize:
      src: /root/.ansible/pull/DietPi/
      dest: /var/www/
      links: yes
      delete: yes
  - name: Recargar nginx
    become: true
    ansible.builtin.service:
      name: nginx
      state: reloaded
      enabled: true